#!/usr/bin/env bash
# save_context.sh — update CLAUDE.md and docs/session_handoff.md with current run state
# Run at end of every session: bash scripts/save_context.sh
set -euo pipefail
cd "$(dirname "$0")/.."

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")

# ── Detect active run ──────────────────────────────────────────────────────────
ACTIVE_PID=$(ps aux | grep "[r]un_backtest" | awk '{print $2}' | head -1)
ACTIVE_LOG=$(ls -t artifacts/logs/full_run_v*.log 2>/dev/null | head -1 || echo "none")

if [ -n "$ACTIVE_PID" ]; then
    PROGRESS=$(grep -aE "Walk-forward:.*[0-9]+/147" "$ACTIVE_LOG" 2>/dev/null | tail -1 | grep -oE "[0-9]+/147" || echo "unknown")
    RUN_STATUS="RUNNING — PID $ACTIVE_PID, progress $PROGRESS, log: $ACTIVE_LOG"
else
    RUN_STATUS="NOT RUNNING — last log: $ACTIVE_LOG"
fi

# ── Read last selection diagnostics ───────────────────────────────────────────
DIAG_FILE="artifacts/reports/selection_diagnostics.json"
if [ -f "$DIAG_FILE" ]; then
    IC=$(python3 -c "import json; d=json.load(open('$DIAG_FILE')); print(f\"{d.get('within_sector_ic',0):.4f}\")" 2>/dev/null || echo "n/a")
    CAGR_SEL=$(python3 -c "
import csv
with open('artifacts/reports/strategy_comparison.csv') as f:
    for row in csv.DictReader(f):
        if row['strategy'] == 'RL Portfolio':
            print(f\"{float(row['cagr'])*100:.2f}%\")
            break
" 2>/dev/null || echo "n/a")
else
    IC="n/a"; CAGR_SEL="n/a"
fi

echo "Context saved at $TIMESTAMP"
echo "Active run: $RUN_STATUS"
echo "Last selection IC: $IC | CAGR: $CAGR_SEL"

# ── Update CLAUDE.md active-state section ─────────────────────────────────────
# Replace just the timestamp and run status lines (lines between the markers)
python3 - <<PYEOF
import re, pathlib

content = pathlib.Path('CLAUDE.md').read_text()

new_state = f"""## Current State (updated {TIMESTAMP})

### Active run
- **full_rl v5** — {RUN_STATUS}
- Config: \`adaptive_top_k: true\`, \`trend_gate_enabled: true\`, \`trend_gate_pctile: 0.80\`
- ETA: ~58h (CVXPY inside RL loop is single-threaded — more cores don't help)
- **Do not relaunch or change selection config until v5 completes**
- Log: \`{ACTIVE_LOG}\`"""

content = re.sub(
    r'## Current State \(updated .*?\).*?(?=\n---)',
    new_state,
    content,
    flags=re.DOTALL,
)
pathlib.Path('CLAUDE.md').write_text(content)
print("CLAUDE.md updated")
PYEOF

# ── Update session_handoff.md timestamp ───────────────────────────────────────
python3 - <<PYEOF
import pathlib
p = pathlib.Path('docs/session_handoff.md')
content = p.read_text()
content = content.replace(
    content.split('\n')[2],  # "Auto-generated..." line
    f'> Auto-generated by \`scripts/save_context.sh\`. Last updated: {TIMESTAMP}.'
)
p.write_text(content)
print("docs/session_handoff.md updated")
PYEOF

echo "Done. Next: git add CLAUDE.md docs/session_handoff.md && git commit -m 'chore: update session context' && git push origin codebase-analysis"
